.TH "Dokumentacja katalogu /home/karolina/Pulpit/pamsi8/prj" 3 "So, 24 maj 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu /home/karolina/Pulpit/pamsi8/prj \- 
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBmain\&.cpp\fP"
.br
.RI "\fIGlowny plik programu\&. \fP"
.ti -1c
.RI "plik \fBplecak\&.cpp\fP"
.br
.RI "\fIFunkcje do klasy plecak\&. \fP"
.ti -1c
.RI "plik \fBplecak\&.h\fP"
.br
.RI "\fIDefinicja klasy plecak\&. \fP"
.in -1c
