.TH "Dokumentacja katalogu /home/karolina/Pulpit/pamsi8/prj/Debug" 3 "So, 24 maj 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu /home/karolina/Pulpit/pamsi8/prj/Debug \- 
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBmain\&.d\fP"
.br
.ti -1c
.RI "plik \fBplecak\&.d\fP"
.br
.in -1c
