.TH "/home/karolina/Pulpit/pamsi8/prj/main.cpp" 3 "So, 24 maj 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/pamsi8/prj/main.cpp \- 
.PP
Glowny plik programu\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'plecak\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "\fIGłówna funkcja programu\&. W funkcji main: -tworzona jest zmienna typu plecak -uzytkownik zostaje zapytany o jakiej pojemnosci ma byc plecak i ile przedmiotow chce tam wlozyc -sprawdzenie poprawnosci dzialania funkcji oblicz -sprawdzenie poprawnosci dzialania funkcji przedmioty -sprawdzenie poprawnosci dzialania funkcji wartosc -wypisanie na konsoli wyniku zapakowania plecaka oraz jakie elementy sie w nim znajduja\&. \fP"
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "int main ()"

.PP
Definicja w linii 31 pliku main\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
