.TH "Dokumentacja katalogu /home/karolina/Pulpit/astar/prj" 3 "N, 25 maj 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu /home/karolina/Pulpit/astar/prj \- 
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBGraf\&.cpp\fP"
.br
.RI "\fIFunkcje do klasy \fBGraf\fP\&. \fP"
.ti -1c
.RI "plik \fBGraf\&.h\fP"
.br
.RI "\fIDefinicja klasy \fBGraf\fP\&. \fP"
.ti -1c
.RI "plik \fBmain\&.cpp\fP"
.br
.RI "\fIGlowny plik programu\&. \fP"
.ti -1c
.RI "plik \fBpara\&.cpp\fP"
.br
.RI "\fIFunkcje klasy para\&. \fP"
.ti -1c
.RI "plik \fBpara\&.h\fP"
.br
.RI "\fIDefinicja klasy para\&. \fP"
.in -1c
