.TH "/home/karolina/Pulpit/astar/prj/Graf.h" 3 "N, 25 maj 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/astar/prj/Graf.h \- 
.PP
Definicja klasy \fBGraf\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'para\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <list>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBGraf\fP"
.br
.RI "\fIModeluje pojęcie \fBGraf\fP\&. Klasa modeluje pojęcie graf \&. Jej atrybutem jest pole zawierajace liste sasedztwa\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik zawiera definicję klasy \fBGraf\fP Jest to klasa glowna , ktora wykorzystuje klase para\&. 
.PP
Definicja w pliku \fBGraf\&.h\fP\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
