.TH "/home/karolina/Pulpit/astar/prj/main.cpp" 3 "N, 25 maj 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/astar/prj/main.cpp \- 
.PP
Glowny plik programu\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Graf\&.h'\fP
.br
\fC#include <ctime>\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "\fIGłówna funkcja programu W funkcji main: -tworzona jest zmienna typu \fBGraf\fP -dodana do niej zostaja para wierzcholkow -dodanie krawedzi -sprawdzenie poprawnosci dzialania funkcji sasiad (wypisanie sasiadujacych wierzchoklow z wybranym) -sprawdzenie poprawnosci dzialania funkcji usun krawedz -sprawdzenie zawartosci tablicy -zmierzenie czasu dzialania funkcji DFS,BFS i astar\&. \fP"
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "int main ()"

.PP
Definicja w linii 31 pliku main\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
