.TH "/home/karolina/Pulpit/astar/prj/para.h" 3 "N, 25 maj 2014" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/karolina/Pulpit/astar/prj/para.h \- 
.PP
Definicja klasy para\&.  

.SH SYNOPSIS
.br
.PP
.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBpara\fP"
.br
.RI "\fIModeluje pojęcie para\&. Klasa modeluje pojęcie para \&. Jej atrybutem sa pola zawierajace numer wierzcholka i jego wage\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik zawiera definicję klasy para Jest to klasa pomocnicza wykorzystywana w klasie \fBGraf\fP\&. 
.PP
Definicja w pliku \fBpara\&.h\fP\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla My Project\&.
